//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Statuses
    {
        public long ClientID { get; set; }
        public long Id { get; set; }
        public long Application_Id { get; set; }
        public int Status_Type_Id { get; set; }
        public Nullable<int> Direct_Cert_Id { get; set; }
        public Nullable<bool> Precertified { get; set; }
    }
}
