//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Signers
    {
        public long ClientID { get; set; }
        public long Id { get; set; }
        public long Application_Id { get; set; }
        public long App_Member_Id { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Cell_Phone { get; set; }
        public string Other_Phone { get; set; }
        public string Email { get; set; }
        public string SSN { get; set; }
        public Nullable<bool> No_SSN { get; set; }
        public Nullable<System.DateTime> Signed_Date { get; set; }
        public Nullable<int> Other_Identifier { get; set; }
        public string IP_Address { get; set; }
        public Nullable<bool> Terms_Of_Use_Accepted { get; set; }
        public Nullable<bool> Confirmation_Of_Accuracy { get; set; }
        public string Signature { get; set; }
        public Nullable<System.DateTime> LastUpdatedUTC { get; set; }
        public Nullable<bool> UpdatedBySync { get; set; }
        public Nullable<int> Local_ID { get; set; }
        public bool CloudIDSync { get; set; }
    }
}
