//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Members
    {
        public long ClientID { get; set; }
        public long Id { get; set; }
        public long Application_Id { get; set; }
        public Nullable<int> Ethnic_Id { get; set; }
        public Nullable<long> Customer_Id { get; set; }
        public Nullable<long> Member_Id { get; set; }
        public Nullable<bool> Foster { get; set; }
        public Nullable<bool> Homeless { get; set; }
        public Nullable<bool> Migrant { get; set; }
        public Nullable<bool> Runaway { get; set; }
        public Nullable<bool> NoIncome { get; set; }
        public bool isStudent { get; set; }
        public Nullable<System.DateTime> LastUpdatedUTC { get; set; }
        public Nullable<bool> UpdatedBySync { get; set; }
        public Nullable<int> Local_ID { get; set; }
        public bool CloudIDSync { get; set; }
    }
}
