//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public long ClientID { get; set; }
        public long Id { get; set; }
        public int District_Id { get; set; }
        public int Parent_Id { get; set; }
        public Nullable<int> Household_Size { get; set; }
        public Nullable<bool> Homeless_On_App { get; set; }
        public Nullable<bool> Migrant_On_App { get; set; }
        public Nullable<bool> Runaway_On_App { get; set; }
        public string Beneficiary_Name { get; set; }
        public string Case_Number { get; set; }
        public Nullable<double> Total_Income { get; set; }
        public Nullable<int> Total_Frequency_Id { get; set; }
        public Nullable<bool> Fee_Waiver { get; set; }
        public Nullable<int> Language_Id { get; set; }
        public Nullable<System.DateTime> LastUpdatedUTC { get; set; }
        public Nullable<bool> UpdatedBySync { get; set; }
        public Nullable<int> Local_ID { get; set; }
        public bool CloudIDSync { get; set; }
        public bool Entered { get; set; }
        public Nullable<bool> Updated { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
    }
}
