//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashResult
    {
        public long ClientID { get; set; }
        public long Id { get; set; }
        public long POS_Id { get; set; }
        public long Emp_Cashier_Id { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> OpenDateLocal { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> CloseDateLocal { get; set; }
        public Nullable<double> TotalCash { get; set; }
        public Nullable<double> OverShort { get; set; }
        public Nullable<double> Additional { get; set; }
        public Nullable<double> PaidOuts { get; set; }
        public Nullable<double> OpenAmount { get; set; }
        public Nullable<double> CloseAmount { get; set; }
        public Nullable<double> Sales { get; set; }
        public Nullable<bool> Finished { get; set; }
        public byte[] OpenBlob { get; set; }
        public byte[] CloseBlob { get; set; }
        public Nullable<int> CashDrawer_Id { get; set; }
        public string PartitionId { get; set; }
        public string PartitionOffset { get; set; }
        public Nullable<System.DateTime> LastUpdatedUTC { get; set; }
        public Nullable<bool> UpdatedBySync { get; set; }
        public Nullable<int> Local_ID { get; set; }
        public bool CloudIDSync { get; set; }
    }
}
