//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashierPayment
    {
        public long ClientID { get; set; }
        public Nullable<long> DISTID { get; set; }
        public Nullable<long> SCHID { get; set; }
        public Nullable<long> CSTID { get; set; }
        public Nullable<long> EMPID { get; set; }
        public long POSID { get; set; }
        public string DistrictName { get; set; }
        public string SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string EmpUserID { get; set; }
        public string CashierName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string CustUserID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Middle { get; set; }
        public Nullable<int> TransType { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public string Comments { get; set; }
        public Nullable<double> TotalCashPayments { get; set; }
        public Nullable<double> TotalChecks { get; set; }
        public Nullable<double> TotalCredits { get; set; }
        public Nullable<double> OnlineCreditPayments { get; set; }
        public Nullable<double> OnlineACHPayments { get; set; }
        public Nullable<double> OnlineACHReturns { get; set; }
        public Nullable<double> Refunds { get; set; }
        public Nullable<double> AccountPayments { get; set; }
        public Nullable<double> CashSaleMonies { get; set; }
        public Nullable<double> TotalMonies { get; set; }
        public Nullable<double> TotalDeposit { get; set; }
        public Nullable<int> LineCount { get; set; }
        public int GroupType { get; set; }
        public string FullName { get; set; }
    }
}
