//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long ClientID { get; set; }
        public long ID { get; set; }
        public long District_Id { get; set; }
        public Nullable<long> Language_Id { get; set; }
        public Nullable<long> Grade_Id { get; set; }
        public Nullable<long> Homeroom_Id { get; set; }
        public Nullable<bool> isStudent { get; set; }
        public string UserID { get; set; }
        public string PIN { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Middle { get; set; }
        public string Gender { get; set; }
        public string SSN { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public Nullable<int> LunchType { get; set; }
        public Nullable<bool> AllowAlaCarte { get; set; }
        public Nullable<bool> CashOnly { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public string SchoolDat { get; set; }
        public bool isDeleted { get; set; }
        public string ExtraInfo { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> ACH { get; set; }
        public Nullable<bool> isSnack { get; set; }
        public Nullable<bool> isStudentWorker { get; set; }
        public Nullable<bool> isVeteran { get; set; }
        public Nullable<int> Ethnicity_Id { get; set; }
        public Nullable<int> Disability { get; set; }
        public Nullable<bool> isHomeless { get; set; }
        public Nullable<int> Disabled { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> NotInDistrict { get; set; }
        public Nullable<long> MealPlan_Id { get; set; }
        public Nullable<int> MealsLeft { get; set; }
        public string STUD_MGMT_ID { get; set; }
        public Nullable<System.DateTime> DeactiveDate { get; set; }
        public Nullable<System.DateTime> ReactiveDate { get; set; }
        public Nullable<System.DateTime> GradDate { get; set; }
        public Nullable<bool> GraduationDateSet { get; set; }
        public Nullable<System.DateTime> CreationDateLocal { get; set; }
        public Nullable<System.DateTime> DeactiveDateLocal { get; set; }
        public Nullable<System.DateTime> ReactiveDateLocal { get; set; }
        public Nullable<System.DateTime> LastUpdatedUTC { get; set; }
        public Nullable<bool> UpdatedBySync { get; set; }
        public Nullable<int> Local_ID { get; set; }
        public bool CloudIDSync { get; set; }
        public Nullable<System.DateTime> MSAStudentSyncDateUTC { get; set; }
    }
}
