//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBalance
    {
        public long ROWID { get; set; }
        public string UserID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<bool> isActive { get; set; }
        public bool isPrimary { get; set; }
        public string SchoolName { get; set; }
        public string Grade { get; set; }
        public string Homeroom { get; set; }
        public double ABalance { get; set; }
        public double MBalance { get; set; }
        public double BonusBalance { get; set; }
        public Nullable<long> SCHID { get; set; }
        public long HRID { get; set; }
        public long GRID { get; set; }
        public Nullable<long> ClientID { get; set; }
        public int LunchType { get; set; }
        public Nullable<long> CustomerID { get; set; }
    }
}
