//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLog
    {
        public long ClientID { get; set; }
        public long Id { get; set; }
        public long Customer_Id { get; set; }
        public Nullable<long> Emp_Changed_Id { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public string Notes { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> ChangedDateLocal { get; set; }
        public Nullable<System.DateTime> LastUpdatedUTC { get; set; }
        public Nullable<bool> UpdatedBySync { get; set; }
        public Nullable<int> Local_ID { get; set; }
        public bool CloudIDSync { get; set; }
    }
}
