//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyCashier
    {
        public long ClientID { get; set; }
        public long CASHRESID { get; set; }
        public Nullable<long> CUSTID { get; set; }
        public long POSID { get; set; }
        public Nullable<long> SCHID { get; set; }
        public string POSName { get; set; }
        public string SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string LoginName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Middle { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<double> OpenAmount { get; set; }
        public Nullable<double> CloseAmount { get; set; }
        public Nullable<double> Deposit { get; set; }
        public Nullable<double> PaidOuts { get; set; }
        public Nullable<double> Additional { get; set; }
        public Nullable<double> TotalCash { get; set; }
        public Nullable<double> OverShort { get; set; }
        public Nullable<double> Sales { get; set; }
        public Nullable<double> Tax { get; set; }
    }
}
