//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositTicket
    {
        public long ClientID { get; set; }
        public long CASHRESID { get; set; }
        public long ORDID { get; set; }
        public int CSTID { get; set; }
        public long POSID { get; set; }
        public Nullable<long> DISTID { get; set; }
        public Nullable<long> SCHID { get; set; }
        public int DepositType { get; set; }
        public int PaymentType { get; set; }
        public string PaymentTypeName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string DistrictName { get; set; }
        public string DistAddress1 { get; set; }
        public string DistAddress2 { get; set; }
        public string DistCity { get; set; }
        public string DistState { get; set; }
        public string DistZip { get; set; }
        public string DistBankName { get; set; }
        public string DistBankAddress1 { get; set; }
        public string DistBankAddress2 { get; set; }
        public string DistBankCity { get; set; }
        public string DistBankState { get; set; }
        public string DistBankZip { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Middle { get; set; }
        public Nullable<int> CheckNumber { get; set; }
        public Nullable<double> CheckAmount { get; set; }
        public Nullable<double> POSCheckAmount { get; set; }
        public Nullable<double> AdminCheckAmount { get; set; }
        public Nullable<double> CreditAmount { get; set; }
        public Nullable<double> POSCreditAmount { get; set; }
        public Nullable<double> AdminCreditAmount { get; set; }
        public Nullable<double> CashAmount { get; set; }
        public Nullable<double> MiscCashAmount { get; set; }
        public Nullable<double> POSCashAmount { get; set; }
        public Nullable<double> AdminCashAmount { get; set; }
        public Nullable<double> POSTotalAmount { get; set; }
        public Nullable<double> AdminTotalAmount { get; set; }
        public Nullable<double> CashOutAmount { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
