//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailCafeSummary
    {
        public Nullable<long> ClientID { get; set; }
        public long ORDID { get; set; }
        public long CASHRESID { get; set; }
        public Nullable<long> SCHID { get; set; }
        public long POSID { get; set; }
        public Nullable<long> EMPID { get; set; }
        public long CUSTID { get; set; }
        public Nullable<System.DateTime> ReportDateTime { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<double> CashSalesByItem { get; set; }
        public Nullable<double> AccountSalesByItem { get; set; }
        public Nullable<double> PreOrderSalesByItem { get; set; }
        public Nullable<double> CashSalesByItemTotal { get; set; }
        public Nullable<double> AccountSalesByItemTotal { get; set; }
        public Nullable<double> PreOrderSalesByItemTotal { get; set; }
        public Nullable<double> PaymentsOnAccount { get; set; }
        public Nullable<double> TotalOnAccount { get; set; }
        public Nullable<double> CashPayments { get; set; }
        public Nullable<double> CashSales { get; set; }
        public Nullable<double> AccountSales { get; set; }
        public Nullable<double> VendingPayments { get; set; }
        public Nullable<double> VendingAcctSales { get; set; }
        public Nullable<double> VendingCashSales { get; set; }
        public Nullable<double> VendingSales { get; set; }
        public Nullable<double> TotalAccountSales { get; set; }
        public Nullable<double> TotalCashSales { get; set; }
        public Nullable<double> Refunds { get; set; }
        public Nullable<double> OverShort { get; set; }
        public Nullable<double> TotalSales { get; set; }
        public Nullable<double> POSDeposit { get; set; }
        public Nullable<double> VendingDeposit { get; set; }
        public Nullable<double> AdminDeposit { get; set; }
        public Nullable<double> OnlineDeposit { get; set; }
        public Nullable<double> Deposit { get; set; }
        public Nullable<double> ChargedOnAccount { get; set; }
        public Nullable<double> TotalCredits { get; set; }
        public Nullable<double> TotalDebits { get; set; }
        public Nullable<double> Revenue { get; set; }
        public Nullable<double> ToAccountFor { get; set; }
        public Nullable<double> AdultPayments { get; set; }
        public Nullable<double> StudentPayments { get; set; }
        public Nullable<double> TaxableSales { get; set; }
        public Nullable<double> TaxableCashSales { get; set; }
        public Nullable<double> TaxableAcctSales { get; set; }
        public Nullable<double> TaxCollected { get; set; }
        public Nullable<double> TaxOnAcctSales { get; set; }
        public Nullable<double> TaxOnCashSales { get; set; }
        public decimal TaxOnPOSales { get; set; }
        public Nullable<double> CreditsOnAccount { get; set; }
        public Nullable<double> OnlinePayments { get; set; }
        public Nullable<double> OnlineCCPayments { get; set; }
        public Nullable<double> OnlineACHPayments { get; set; }
        public Nullable<double> OnlineACHReturns { get; set; }
        public Nullable<double> AccountSubtotal { get; set; }
        public Nullable<double> POSPaymentsOnAccount { get; set; }
        public Nullable<double> AdminPaymentsOnAccount { get; set; }
        public Nullable<double> AdminPaymentsVoided { get; set; }
        public Nullable<double> AdminRefunds { get; set; }
    }
}
