//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailCafeNetChange
    {
        public Nullable<long> ClientID { get; set; }
        public Nullable<long> CSTID { get; set; }
        public Nullable<long> SCHID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ReportDate { get; set; }
        public Nullable<double> NetChange { get; set; }
    }
}
