//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictOption
    {
        public long ClientID { get; set; }
        public long ID { get; set; }
        public long District_Id { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<int> LetterWarning1 { get; set; }
        public Nullable<int> LetterWarning2 { get; set; }
        public Nullable<int> LetterWarning3 { get; set; }
        public Nullable<double> TaxPercent { get; set; }
        public Nullable<bool> isEmployeeTaxable { get; set; }
        public Nullable<bool> isStudentFreeTaxable { get; set; }
        public Nullable<bool> isStudentPaidTaxable { get; set; }
        public Nullable<bool> isStudentRedTaxable { get; set; }
        public Nullable<System.DateTime> StartSchoolYear { get; set; }
        public Nullable<System.DateTime> EndSchoolYear { get; set; }
        public Nullable<System.DateTime> StartForms { get; set; }
        public Nullable<System.DateTime> EndForms { get; set; }
        public Nullable<bool> isMealPlanTaxable { get; set; }
        public Nullable<bool> UsingMealPlan { get; set; }
        public Nullable<bool> UsingMealEqual { get; set; }
        public Nullable<bool> UsingBonus { get; set; }
        public Nullable<bool> BlindCashOut { get; set; }
        public Nullable<bool> isGuestTaxable { get; set; }
        public Nullable<bool> isStudCashTaxable { get; set; }
        public Nullable<int> LetterWarning4 { get; set; }
        public Nullable<int> LetterWarning5 { get; set; }
        public Nullable<int> LetterWarning6 { get; set; }
        public Nullable<int> MaxLetter { get; set; }
        public Nullable<double> LetterResetLimit { get; set; }
        public Nullable<int> LetterResetRule { get; set; }
        public bool ReqSecondAuth { get; set; }
        public int SecondAuthType { get; set; }
        public Nullable<int> CCProcessor_Id { get; set; }
        public Nullable<bool> EnableGlobalVeriFoneUser { get; set; }
        public string LicenseModel { get; set; }
        public string MerchantId { get; set; }
        public string VeriFoneIP { get; set; }
        public Nullable<int> VeriFonePort { get; set; }
        public string VeriFoneUserId { get; set; }
        public string VeriFonePassword { get; set; }
        public Nullable<double> IncomePercentage { get; set; }
        public Nullable<double> FSTANFPercentage { get; set; }
        public Nullable<double> AnnualAmountToQualify { get; set; }
        public Nullable<System.DateTime> ChangedDateLocal { get; set; }
        public Nullable<System.DateTime> LastUpdatedUTC { get; set; }
        public Nullable<bool> UpdatedBySync { get; set; }
        public Nullable<int> Local_ID { get; set; }
        public bool CloudIDSync { get; set; }
    }
}
