//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income_Frequencies
    {
        public int Id { get; set; }
        public string Frequency_Name { get; set; }
        public Nullable<int> Multiplier { get; set; }
    }
}
