//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    
    public partial class Main_Items_View_Result1
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> Qty { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> PaidPrice { get; set; }
        public Nullable<bool> Void { get; set; }
        public Nullable<System.DateTime> ServingDate { get; set; }
        public Nullable<System.DateTime> PickedupDate { get; set; }
    }
}
