//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public long ClientID { get; set; }
        public long ID { get; set; }
        public long Category_Id { get; set; }
        public string ItemName { get; set; }
        public string M_F6_Code { get; set; }
        public Nullable<double> StudentFullPrice { get; set; }
        public Nullable<double> StudentRedPrice { get; set; }
        public Nullable<double> EmployeePrice { get; set; }
        public Nullable<double> GuestPrice { get; set; }
        public Nullable<bool> isTaxable { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<bool> isScaleItem { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<bool> isOnceDay { get; set; }
        public Nullable<int> KitchenItem { get; set; }
        public Nullable<bool> MealEquivItem { get; set; }
        public string UPC { get; set; }
        public string PreOrderDesc { get; set; }
        public string ButtonCaption { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> LastUpdateLocal { get; set; }
        public Nullable<System.DateTime> LastUpdatedUTC { get; set; }
        public Nullable<bool> UpdatedBySync { get; set; }
        public Nullable<int> Local_ID { get; set; }
        public bool CloudIDSync { get; set; }
    }
}
