//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS
    {
        public long ClientID { get; set; }
        public long ID { get; set; }
        public long School_Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ShortCutsNumber { get; set; }
        public byte[] ShortCutsBlob { get; set; }
        public Nullable<bool> isQuickSale { get; set; }
        public Nullable<int> Quick1 { get; set; }
        public Nullable<int> Quick2 { get; set; }
        public Nullable<int> Quick3 { get; set; }
        public Nullable<bool> isMealEqual { get; set; }
        public Nullable<int> MealEqual1 { get; set; }
        public Nullable<int> MealEqual2 { get; set; }
        public Nullable<int> MealEqual3 { get; set; }
        public Nullable<bool> EnableCCProcessing { get; set; }
        public string VeriFoneUserId { get; set; }
        public string VeriFonePassword { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> LastUpdatedUTC { get; set; }
        public Nullable<bool> UpdatedBySync { get; set; }
        public Nullable<int> Local_ID { get; set; }
        public bool CloudIDSync { get; set; }
    }
}
