//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldItem
    {
        public long clientid { get; set; }
        public long ItemMenuID { get; set; }
        public Nullable<long> MenuID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> CategoryTypeID { get; set; }
        public long POSID { get; set; }
        public Nullable<long> SCHID { get; set; }
        public Nullable<long> PRIMSCHID { get; set; }
        public Nullable<long> EMPCASHID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime GDate { get; set; }
        public Nullable<int> TransType { get; set; }
        public string CategoryTypeName { get; set; }
        public string CategoryName { get; set; }
        public string MenuItem { get; set; }
        public int LunchType { get; set; }
        public string LunchTypeStatus { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> RegularPrice { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> SoldType { get; set; }
        public Nullable<double> Total { get; set; }
        public string PreOrderStatus { get; set; }
        public Nullable<bool> PreOrderPickup { get; set; }
    }
}
