//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemOptions
    {
        public long ClientID { get; set; }
        public Nullable<int> PackageType { get; set; }
        public Nullable<bool> Discount { get; set; }
        public Nullable<bool> AllowCreditCard { get; set; }
        public Nullable<bool> AllowVending { get; set; }
        public Nullable<bool> UsingPreOrder { get; set; }
        public Nullable<int> MSADistrictID { get; set; }
        public string PreOrderUserName { get; set; }
        public string PreOrderPassword { get; set; }
        public Nullable<int> POPickupMode { get; set; }
        public Nullable<int> AutoReCalc { get; set; }
        public long ID { get; set; }
        public Nullable<System.DateTime> LastUpdatedUTC { get; set; }
        public Nullable<bool> UpdatedBySync { get; set; }
        public Nullable<int> Local_ID { get; set; }
        public bool CloudIDSync { get; set; }
    }
}
