//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoidsD
    {
        public long ROWID { get; set; }
        public long ClientID { get; set; }
        public Nullable<long> SCHID { get; set; }
        public Nullable<long> ORDEMPID { get; set; }
        public Nullable<long> CSTID { get; set; }
        public Nullable<long> MODEMPID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> GDate { get; set; }
        public string SchoolName { get; set; }
        public string SchoolID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Middle { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> VoidTime { get; set; }
        public Nullable<bool> VoidOrder { get; set; }
        public Nullable<int> VoidItem { get; set; }
        public Nullable<int> TransType { get; set; }
        public Nullable<double> ACredit { get; set; }
        public Nullable<double> ADebit { get; set; }
        public Nullable<double> MCredit { get; set; }
        public Nullable<double> MDebit { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> TaxPrice { get; set; }
        public Nullable<double> Total { get; set; }
        public string Cashier { get; set; }
        public string Notes { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> SortDate { get; set; }
    }
}
